services:
  hogger:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://admin:admin@mongo:27017/admin
      - RABBITMQ_URI=amqp://guest:guest@rabbitmq:5672/%2f
      - DATABASE_NAME=hogger
      - PORT=3000
      - BEARER_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlIjoiYXBpIiwicm9sZSI6ImFkbWluIiwiaXNzdWVkQnkiOiJ0b2tlbi1nZW5lcmF0b3IiLCJpYXQiOjE3NDUzNDc3MTN9.ttTOeBN7RPVOreIfJpt7elaePBNVPiYWMp234r8zglo
    networks:
      - hogger-net
    depends_on:
      - mongo
      - rabbitmq
    restart: on-failure

  hogger-worker:
    build: .
    command: ./hogger-worker
    restart: on-failure
    environment:
      - MONGODB_URI=mongodb://admin:admin@mongo:27017/admin
      - RABBITMQ_URI=amqp://guest:guest@rabbitmq:5672/%2f
      - DATABASE_NAME=hogger
      - PORT=3000
      - BEARER_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlIjoiYXBpIiwicm9sZSI6ImFkbWluIiwiaXNzdWVkQnkiOiJ0b2tlbi1nZW5lcmF0b3IiLCJpYXQiOjE3NDUzNDc3MTN9.ttTOeBN7RPVOreIfJpt7elaePBNVPiYWMp234r8zglo
    networks:
      - hogger-net
    depends_on:
      - mongo
      - rabbitmq

  hogger-bulk-worker:
    build: .
    command: ./hogger-bulk-worker
    restart: on-failure
    deploy:
      replicas: 3
    environment:
      - MONGODB_URI=mongodb://admin:admin@mongo:27017/admin
      - RABBITMQ_URI=amqp://guest:guest@rabbitmq:5672/%2f
      - DATABASE_NAME=hogger
      - PORT=3000
      - BEARER_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlIjoiYXBpIiwicm9sZSI6ImFkbWluIiwiaXNzdWVkQnkiOiJ0b2tlbi1nZW5lcmF0b3IiLCJpYXQiOjE3NDUzNDc3MTN9.ttTOeBN7RPVOreIfJpt7elaePBNVPiYWMp234r8zglo
    networks:
      - hogger-net
    depends_on:
      - mongo
      - rabbitmq

  mongo:
    image: mongo:6.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - hogger-net
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"     
      - "15672:15672"   
    networks:
      - hogger-net
    restart: always

volumes:
  mongo_data:

networks:
  hogger-net:
    driver: bridge
