version: "3.8"

services:
  hogger:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://admin:admin@mongo:27017/admin
      - RABBITMQ_URI=amqp://guest:guest@rabbitmq:5672/%2f
      - DATABASE_NAME=hogger
      - PORT=3000
      - BEARER_TOKEN=your_token_here
    networks:
      - hogger-net
    depends_on:
      - mongo
      - rabbitmq
    restart: on-failure

  hogger-worker:
    build: .
    command: ./hogger-worker
    restart: on-failure
    environment:
      - MONGODB_URI=mongodb://admin:admin@mongo:27017/admin
      - RABBITMQ_URI=amqp://guest:guest@rabbitmq:5672/%2f
      - DATABASE_NAME=hogger
      - PORT=3000
      - BEARER_TOKEN=your_token_here
    networks:
      - hogger-net
    depends_on:
      - mongo
      - rabbitmq

  hogger-bulk-worker:
    build: .
    command: ./hogger-bulk-worker
    restart: on-failure
    deploy:
      replicas: 3
    environment:
      - MONGODB_URI=mongodb://admin:admin@mongo:27017/admin
      - RABBITMQ_URI=amqp://guest:guest@rabbitmq:5672/%2f
      - DATABASE_NAME=hogger
      - PORT=3000
      - BEARER_TOKEN=your_token_here
    networks:
      - hogger-net
    depends_on:
      - mongo
      - rabbitmq

  mongo:
    image: mongo:6.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - hogger-net

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - hogger-net
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - hogger-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - hogger-net

volumes:
  mongo_data:
  grafana_data:

networks:
  hogger-net:
    driver: bridge
