apiVersion: apps/v1
kind: Deployment
metadata:
  name: hogger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hogger
  template:
    metadata:
      labels:
        app: hogger
    spec:
      containers:
        - name: hogger
          image: hogger:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
            - name: MONGODB_URI
              value: mongodb://admin:admin@mongo:27017/admin
            - name: RABBITMQ_URI
              value: amqp://guest:guest@rabbitmq:5672/
            - name: DATABASE_NAME
              value: hogger
            - name: BEARER_TOKEN
              value: your_token_here
---
apiVersion: v1
kind: Service
metadata:
  name: hogger
spec:
  selector:
    app: hogger
  ports:
    - port: 3000
