apiVersion: apps/v1
kind: Deployment
metadata:
  name: hogger-bulk-worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hogger-bulk-worker
  template:
    metadata:
      labels:
        app: hogger-bulk-worker
    spec:
      containers:
        - name: hogger-bulk-worker
          image: hogger:latest
          imagePullPolicy: Never
          command: ["./hogger-bulk-worker"]
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
            - name: MONGODB_URI
              value: mongodb://admin:admin@mongo:27017/admin
            - name: RABBITMQ_URI
              value: amqp://guest:guest@rabbitmq:5672/
            - name: DATABASE_NAME
              value: hogger
            - name: BEARER_TOKEN
              value: your_token_here
